name: workshop-cd
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches: 
    - main
    paths:
      - src/workshop/core/**
      - .github/workflows/workshop_cd.yml
jobs:
  Workshop-Deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }} #setup replace AZURE_SERVICE_PRINCIPAL with the name of your Azure credentials secret in GitHub

      - name: Install az ml & and tools
        run: |
          az extension add -n ml -y --version 2.2.1
          sudo apt install jq
          pip install yq
      
      - name: Run deployment
        uses: ./.github/actions/aml-endpoint-deploy
        with:
          resourceGroup: njs-aia-rg #setup replace azureml with the name of your resource group in Azure
          workspaceName: njs-ws #setup replace ws01ent with the name of your workspace in Azure
          endpointFile: src/workshop/core/scoring/endpoint.yml
          deploymentFile: src/workshop/core/scoring/deployment.yml
          modelVersion: latest
      
      - name: Test deployment
        uses: ./.github/actions/aml-endpoint-test
        with:
          resourceGroup: njs-aia-rg #setup replace azureml with the name of your resource group in Azure
          workspaceName: njs-ws #setup replace ws01ent with the name of your workspace in Azure
          endpointFile: src/workshop/core/scoring/endpoint.yml
          requestFile: src/workshop/core/scoring/scoring_test_request.json
  
      - name: Swap deployment
        uses: ./.github/actions/aml-endpoint-swap
        with:
          resourceGroup: njs-aia-rg #setup replace azureml with the name of your resource group in Azure
          workspaceName: njs-ws #setup replace ws01ent with the name of your workspace in Azure
          endpointFile: src/workshop/core/scoring/endpoint.yml