name: workshop-online-scoring
channels:
  - conda-forge
dependencies:
  - python=3.8.12
  - pip=21.3.1
  - pip:
    - azureml-mlflow==1.38.0
    - azureml-defaults==1.38.0
    - pandas==1.3.5
    - scikit-learn==1.0.2