name: workshop-cd
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches: 
    - main
    paths:
      - src/workshop/core/**
      - .github/workflows/workshop_cd.yml
jobs:
  Workshop-Deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Setup python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: AZ Login
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }} #setup replace AZURE_SERVICE_PRINCIPAL with the name of your Azure credentials secret in GitHub

      - name: Install az ml & and tools
        run: |
          az extension add -n ml -y --version 2.2.1
          sudo apt install jq
          pip install yq
      
      - name: Run deployment
        uses: ./.github/actions/aml-endpoint-deploy
        with:
          resourceGroup: azureml #setup replace azureml with the name of your resource group in Azure
          workspaceName: ws01ent #setup replace ws01ent with the name of your workspace in Azure
          endpointFile: src/workshop/core/scoring/endpoint.yml
          deploymentFile: src/workshop/core/scoring/deployment.yml
          modelVersion: latest
      
      - name: Test deployment
        uses: ./.github/actions/aml-endpoint-test
        with:
          resourceGroup: azureml #setup replace azureml with the name of your resource group in Azure
          workspaceName: ws01ent #setup replace ws01ent with the name of your workspace in Azure
          endpointFile: src/workshop/core/scoring/endpoint.yml
          requestFile: src/workshop/core/scoring/scoring_test_request.json
  
      - name: Swap deployment
        uses: ./.github/actions/aml-endpoint-swap
        with:
          resourceGroup: azureml #setup replace azureml with the name of your resource group in Azure
          workspaceName: ws01ent #setup replace ws01ent with the name of your workspace in Azure
          endpointFile: src/workshop/core/scoring/endpoint.yml